version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: ${DATABASE_HOSTNAME}
      POSTGRES_PORT: ${DATABASE_PORT}
    container_name: straight-db

  fastapi:
    image: straight-api:1.0
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    container_name: straight-api
